"""lotto add two money

Revision ID: 77def6230975
Revises: 20bcfc3e706a
Create Date: 2021-11-29 12:16:20.679562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77def6230975'
down_revision = '20bcfc3e706a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('config')
#     op.drop_table('admin')
    op.add_column('lotto', sa.Column('salesamount', sa.Integer(), nullable=True))
    op.add_column('lotto', sa.Column('totalbonus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotto', 'totalbonus')
    op.drop_column('lotto', 'salesamount')
#     op.create_table('admin',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
#     sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
#     sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Last Login'),
#     sa.Column('email', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
#     sa.Column('avatar', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
#     sa.Column('intro', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
#     sa.PrimaryKeyConstraint('id', name='admin_pkey'),
#     sa.UniqueConstraint('username', name='admin_username_key')
#     )
#     op.create_table('config',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('label', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
#     sa.Column('key', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Unique key for config'),
#     sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
#     sa.Column('status', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='on: 1\\noff: 0'),
#     sa.PrimaryKeyConstraint('id', name='config_pkey'),
#     sa.UniqueConstraint('key', name='config_key_key')
#     )
    # ### end Alembic commands ###
