"""info table alter price_sale to float

Revision ID: f0950885120f
Revises: 88ff2c6b3408
Create Date: 2021-10-05 10:43:18.398207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0950885120f'
down_revision = '88ff2c6b3408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ips', 'goodcnt',
                    type_=sa.SMALLINT(),
                    existing_type=sa.INTEGER(),
                    existing_comment=None,
                    existing_nullable=False,
                    )
    #
    op.alter_column('info', 'price_sale',
                    type_=sa.FLOAT(),
                    existing_type=sa.SMALLINT(),
                    existing_comment=None,
                    existing_nullable=True,
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ips', 'goodcnt',
                    type_=sa.INTEGER(),
                    existing_type=sa.SMALLINT(),
                    existing_comment=None,
                    existing_nullable=False,
                    )
    #
    op.alter_column('info', 'price_sale',
                    type_=sa.SMALLINT(),
                    existing_type=sa.FLOAT(),
                    existing_comment=None,
                    existing_nullable=True,
                    )
