"""info table alter price_sale to float

Revision ID: b64e10a200d9
Revises: 88ff2c6b3408
Create Date: 2021-10-05 10:33:43.793295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b64e10a200d9'
down_revision = '88ff2c6b3408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.drop_table('admin')
    op.alter_column('ips', 'goodcnt',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='good count',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ips', 'goodcnt',
               existing_type=sa.INTEGER(),
               comment='good count',
               existing_nullable=False)
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Last Login'),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('intro', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    sa.UniqueConstraint('username', name='admin_username_key')
    )
    op.create_table('config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Unique key for config'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='on: 1\\noff: 0'),
    sa.PrimaryKeyConstraint('id', name='config_pkey'),
    sa.UniqueConstraint('key', name='config_key_key')
    )
    # ### end Alembic commands ###
